name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, metadata, repositories
          plugin_traffic: yes
          plugin_languages: yes
